name: Update

on:
  push:
    branches:
    - master

jobs:
  update:
    runs-on:
    - self-hosted
    - updater
      # unique label for runner created specifically for this job
      # "updater" here is the name of the job
    - ${{github.run_id}}-${{github.run_attempt}}-update

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Save image name
      run: echo "image=vkotify:$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build image
      run: DOCKER_BUILDKIT=1 docker build -t ${{ env.image }} .

    - name: Update service
      run: docker service update vkotify --image ${{ env.image }} --update-failure-action rollback --rollback-failure-action continue | tee /tmp/capture.out

    - name: Exit if rollback happened
      run: if [ "$(cat /tmp/capture.out | grep -c '^rollback:')" -ge 1 ]; then echo 'Rollback occurred'; exit 1; fi
